// chat.js — engineer-to-engineer chat router for the Zammad notification proxy.
// Mounted from server.js:  app.use('/api/chat', createChatRouter({ pool, sendPush, lookupDeviceToken }))
//
// Adapted from PROXY_CHAT_API.md to this deployment: MariaDB (shared pool) instead
// of sqlite, and the existing APNs provider from server.js. See PROXY_CHAT_API.md
// in the iOS app repo for the client contract (ChatService.swift).
//
// Protocol level: v4 + v3.1 deletion — direct messages, groups, attachments and
// per-device keys, plus message/conversation deletion. Bodies, group keys and attachment blobs are end-to-end encrypted by the
// client; the proxy stores them verbatim and can never read them.
//
// v4 changes the key model from one key per *user* to one key per *device*, so
// an agent can use the app on an iPhone and an iPad at the same time:
//
//   chat_devices          one row per (user, install): public key + push id
//   chat_message_keys     a direct message's random key, wrapped per device
//   chat_group_device_keys the group key, wrapped per device
//
// A direct message body is sealed once with a random message key; that key is
// then wrapped for every device of the recipient *and* every other device of
// the sender, so all of the sender's own devices can read their own history.
// Group bodies stay sealed with the group key, which is wrapped per device.
//
// Every request identifies the calling device with an X-Device-Id header.

const express = require('express');
const crypto = require('crypto');

// Attachment blobs arrive base64-encoded inside the JSON body. 10 MB of raw
// data (the app's own limit) is ~13.4 MB of base64, so cap a little above that.
const MAX_ATTACHMENT_BASE64 = 15 * 1024 * 1024;
const JSON_BODY_LIMIT = '20mb';

module.exports = function createChatRouter({ pool, sendPush, lookupDeviceToken }) {
    // Simple in-process cache of validated Zammad tokens (url+token -> zammad user id).
    const authCache = new Map(); // cacheKey -> { userId, expires }
    const AUTH_TTL_MS = 10 * 60 * 1000;

    // Basic per-user send rate limiting (60 sends / minute).
    const sendCounters = new Map(); // chatUserId -> { count, windowStart }
    const SEND_LIMIT = 60;
    const SEND_WINDOW_MS = 60 * 1000;

    function normalizeUrl(raw) {
        let url = (raw || '').trim().toLowerCase().replace(/\/+$/, '');
        if (!url) return '';
        if (!url.startsWith('http')) url = 'https://' + url;
        return url;
    }

    // Run a schema migration that is expected to fail once it has been applied
    // (duplicate column / duplicate index). Anything else is a real error.
    async function migrate(conn, sql, description) {
        try {
            await conn.query(sql);
            console.log(`[Chat] Migration applied: ${description}.`);
        } catch (e) {
            if (/duplicate column|duplicate key name/i.test(e.message)) return;
            throw e;
        }
    }

    // Ensure the chat tables exist. Called once at startup from server.js.
    async function initSchema() {
        let conn;
        try {
            conn = await pool.getConnection();
            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_users (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    instance_url VARCHAR(255) NOT NULL,
                    zammad_user_id INT NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    email VARCHAR(255),
                    proxy_user_id VARCHAR(255),
                    public_key TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY uniq_instance_user (instance_url, zammad_user_id)
                )
            `);
            // Migration: add public_key to a pre-existing table (v2, E2E encryption).
            await migrate(conn, 'ALTER TABLE chat_users ADD COLUMN public_key TEXT', "chat_users.public_key");
            // chat_users.public_key and .proxy_user_id are superseded by chat_devices
            // (v4) and are no longer read or written. They are left in place rather
            // than dropped so no deployment loses data on upgrade.

            // v4: one row per device. device_id is generated by the client and is
            // stable for the life of an install (it lives beside the private key in
            // the Keychain, so a reinstall that keeps the Keychain keeps the row).
            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_devices (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    chat_user_id INT NOT NULL,
                    device_id VARCHAR(64) NOT NULL,
                    public_key TEXT NOT NULL,
                    proxy_user_id VARCHAR(255),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    UNIQUE KEY uniq_user_device (chat_user_id, device_id),
                    INDEX idx_device_user (chat_user_id)
                )
            `);

            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_messages (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    from_user_id INT NOT NULL,
                    to_user_id INT NULL,
                    group_id INT NULL,
                    body TEXT NOT NULL,
                    ticket_id INT,
                    ticket_number VARCHAR(64),
                    attachment_id BIGINT NULL,
                    attachment_name VARCHAR(255) NULL,
                    attachment_mime VARCHAR(128) NULL,
                    deleted TINYINT(1) NOT NULL DEFAULT 0,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    read_at TIMESTAMP NULL,
                    INDEX idx_msg_pair (from_user_id, to_user_id, id),
                    INDEX idx_msg_group (group_id, id)
                )
            `);
            // Migrations for a pre-existing v2 table (group + attachment support).
            await migrate(conn, 'ALTER TABLE chat_messages ADD COLUMN group_id INT NULL', 'chat_messages.group_id');
            await migrate(conn, 'ALTER TABLE chat_messages ADD COLUMN attachment_id BIGINT NULL', 'chat_messages.attachment_id');
            await migrate(conn, 'ALTER TABLE chat_messages ADD COLUMN attachment_name VARCHAR(255) NULL', 'chat_messages.attachment_name');
            await migrate(conn, 'ALTER TABLE chat_messages ADD COLUMN attachment_mime VARCHAR(128) NULL', 'chat_messages.attachment_mime');
            await migrate(conn, 'ALTER TABLE chat_messages ADD INDEX idx_msg_group (group_id, id)', 'chat_messages idx_msg_group');
            // v3.1: tombstone flag for messages the sender deleted for everyone.
            await migrate(conn, 'ALTER TABLE chat_messages ADD COLUMN deleted TINYINT(1) NOT NULL DEFAULT 0', 'chat_messages.deleted');
            // Group messages have no recipient — to_user_id must be nullable.
            // Only ALTER when it isn't already: MODIFY rebuilds the table, and
            // chat_messages is the one table that actually grows.
            const nullable = await conn.query(`
                SELECT IS_NULLABLE FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'chat_messages' AND COLUMN_NAME = 'to_user_id'
            `);
            if (nullable[0] && String(nullable[0].IS_NULLABLE).toUpperCase() === 'NO') {
                await conn.query('ALTER TABLE chat_messages MODIFY COLUMN to_user_id INT NULL');
                console.log('[Chat] Migration applied: chat_messages.to_user_id is now nullable.');
            }

            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_groups (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    instance_url VARCHAR(255) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    creator_id INT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX idx_group_instance (instance_url)
                )
            `);
            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_group_members (
                    group_id INT NOT NULL,
                    user_id INT NOT NULL,
                    wrapped_key TEXT,
                    PRIMARY KEY (group_id, user_id),
                    INDEX idx_group_member_user (user_id)
                )
            `);
            // v4: a direct message's random body key, wrapped once per device that
            // is allowed to read it (every device of the recipient, and every other
            // device of the sender). Deleted with the message by retention.js.
            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_message_keys (
                    message_id BIGINT NOT NULL,
                    device_id INT NOT NULL,
                    wrapped_key TEXT NOT NULL,
                    PRIMARY KEY (message_id, device_id),
                    INDEX idx_msgkey_device (device_id)
                )
            `);
            // v4: the group key wrapped per device. wrapper_public_key is the public
            // key of the device that did the wrapping, so the reader knows which
            // key to run the ECDH against.
            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_group_device_keys (
                    group_id INT NOT NULL,
                    device_id INT NOT NULL,
                    wrapped_key TEXT NOT NULL,
                    wrapper_public_key TEXT NOT NULL,
                    PRIMARY KEY (group_id, device_id),
                    INDEX idx_groupkey_device (device_id)
                )
            `);
            // v4: the sending device's public key, for the recipient's ECDH.
            await migrate(conn, 'ALTER TABLE chat_messages ADD COLUMN sender_public_key TEXT NULL', 'chat_messages.sender_public_key');

            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_group_reads (
                    group_id INT NOT NULL,
                    user_id INT NOT NULL,
                    last_read_message_id BIGINT NOT NULL DEFAULT 0,
                    PRIMARY KEY (group_id, user_id)
                )
            `);
            await conn.query(`
                CREATE TABLE IF NOT EXISTS chat_attachments (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    instance_url VARCHAR(255) NOT NULL,
                    uploader_id INT NOT NULL,
                    data LONGBLOB NOT NULL,
                    filename VARCHAR(255),
                    mime_type VARCHAR(128),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX idx_attachment_instance (instance_url)
                )
            `);
            console.log("[Chat] Tables are ready (users, messages, groups, group members/reads, attachments).");
        } finally {
            if (conn) conn.release();
        }
    }

    // ISO 8601 UTC, matching the app's .iso8601 decoder.
    function isoUTC(value) {
        if (!value) return null;
        const d = (value instanceof Date) ? value : new Date(value);
        return d.toISOString().replace(/\.\d{3}Z$/, 'Z');
    }

    const num = (v) => (v != null ? Number(v) : null);

    const toDeviceJson = (d) => ({
        id: Number(d.id),
        public_key: d.public_key,
    });

    // `devices` is attached by attachDevices(); a user with no registered device
    // yet serialises as an empty list, which the client reads as "can't encrypt
    // to this colleague".
    const toUserJson = (u) => ({
        id: Number(u.id),
        zammad_user_id: u.zammad_user_id,
        name: u.name,
        email: u.email,
        devices: Array.isArray(u.devices) ? u.devices.map(toDeviceJson) : [],
    });

    const toMessageJson = (m) => ({
        id: Number(m.id),
        from_user_id: Number(m.from_user_id),
        to_user_id: num(m.to_user_id),
        group_id: num(m.group_id),
        from_user_name: m.from_user_name != null ? m.from_user_name : null,
        body: m.body,
        ticket_id: num(m.ticket_id),
        ticket_number: m.ticket_number != null ? String(m.ticket_number) : null,
        attachment_id: num(m.attachment_id),
        attachment_name: m.attachment_name != null ? m.attachment_name : null,
        attachment_mime: m.attachment_mime != null ? m.attachment_mime : null,
        created_at: isoUTC(m.created_at),
        // v3.1: the sender deleted this one for everyone; body is empty and the
        // client renders a "Message deleted" tombstone in its place.
        deleted: !!m.deleted,
        // v4: the calling device's copy of the body key, and the public key to
        // unwrap it against. Null for group messages (the group key is used) and
        // for direct messages this device was not a recipient of.
        sender_public_key: m.sender_public_key != null ? m.sender_public_key : null,
        wrapped_key: m.wrapped_key != null ? m.wrapped_key : null,
    });

    // Every message SELECT joins the sender so group rendering has a display name,
    // and the calling device's wrapped body key (parameter: chat_devices.id).
    const MESSAGE_SELECT = `
        SELECT m.*, u.name AS from_user_name, k.wrapped_key
        FROM chat_messages m
        LEFT JOIN chat_users u ON u.id = m.from_user_id
        LEFT JOIN chat_message_keys k ON k.message_id = m.id AND k.device_id = ?
    `;

    // --- Device helpers --------------------------------------------------

    // Fills in `devices` on a list of chat_users rows with one query.
    async function attachDevices(conn, users) {
        if (!users.length) return users;
        const ids = users.map((u) => Number(u.id));
        const rows = await conn.query(
            `SELECT id, chat_user_id, public_key FROM chat_devices
             WHERE chat_user_id IN (${ids.map(() => '?').join(',')})
             ORDER BY id`,
            ids
        );
        const byUser = new Map();
        for (const row of rows) {
            const key = Number(row.chat_user_id);
            if (!byUser.has(key)) byUser.set(key, []);
            byUser.get(key).push(row);
        }
        for (const user of users) user.devices = byUser.get(Number(user.id)) || [];
        return users;
    }

    async function devicesOfUsers(conn, userIds) {
        const ids = [...new Set(userIds.map(Number).filter(Boolean))];
        if (!ids.length) return [];
        return conn.query(
            `SELECT id, chat_user_id, public_key, proxy_user_id FROM chat_devices
             WHERE chat_user_id IN (${ids.map(() => '?').join(',')})`,
            ids
        );
    }

    // Validate the caller's Zammad token against their own instance.
    async function authenticate(req, res, next) {
        try {
            const instanceUrl = normalizeUrl(req.get('X-Zammad-Url'));
            const authHeader = req.get('Authorization') || '';
            if (!instanceUrl || !authHeader.startsWith('Token ')) return res.status(401).end();

            const cacheKey = crypto.createHash('sha256').update(instanceUrl + '|' + authHeader).digest('hex');
            const cached = authCache.get(cacheKey);
            if (cached && cached.expires > Date.now()) {
                req.zammad = { instanceUrl, userId: cached.userId };
                return next();
            }

            const controller = new AbortController();
            const timer = setTimeout(() => controller.abort(), 10000);
            let resp;
            try {
                resp = await fetch(`${instanceUrl}/api/v1/users/me`, {
                    headers: { Authorization: authHeader },
                    signal: controller.signal,
                });
            } finally {
                clearTimeout(timer);
            }
            if (!resp.ok) return res.status(401).end();
            const me = await resp.json();
            if (!me || typeof me.id !== 'number') return res.status(401).end();

            authCache.set(cacheKey, { userId: me.id, expires: Date.now() + AUTH_TTL_MS });
            req.zammad = { instanceUrl, userId: me.id };
            next();
        } catch (e) {
            console.error('[Chat] auth error:', e.message);
            res.status(401).end();
        }
    }

    // The caller's directory row, with the calling device resolved from the
    // X-Device-Id header. `deviceRowId` is 0 when the header is missing or the
    // device isn't registered yet — the message queries then simply return no
    // wrapped key, which the client renders as "can't decrypt on this device".
    async function callerChatUser(req) {
        let conn;
        try {
            conn = await pool.getConnection();
            const rows = await conn.query(
                'SELECT * FROM chat_users WHERE instance_url = ? AND zammad_user_id = ?',
                [req.zammad.instanceUrl, req.zammad.userId]
            );
            const me = rows[0] || null;
            if (!me) return null;

            const deviceKey = (req.get('X-Device-Id') || '').trim();
            let device = null;
            if (deviceKey) {
                const drows = await conn.query(
                    'SELECT * FROM chat_devices WHERE chat_user_id = ? AND device_id = ?',
                    [me.id, deviceKey]
                );
                device = drows[0] || null;
            }
            me.device = device;
            me.deviceRowId = device ? Number(device.id) : 0;
            return me;
        } finally {
            if (conn) conn.release();
        }
    }

    // --- Group helpers ---------------------------------------------------

    async function isGroupMember(conn, groupId, userId) {
        const rows = await conn.query(
            'SELECT 1 AS ok FROM chat_group_members WHERE group_id = ? AND user_id = ?',
            [groupId, userId]
        );
        return rows.length > 0;
    }

    // The group as seen by one *device*: that device's own wrapped copy of the
    // group key, plus the public key of the device that wrapped it.
    async function groupJson(conn, group, viewerDeviceRowId) {
        const members = await conn.query(`
            SELECT u.*
            FROM chat_group_members m
            JOIN chat_users u ON u.id = m.user_id
            WHERE m.group_id = ?
            ORDER BY u.name
        `, [group.id]);
        await attachDevices(conn, members);

        let mine = null;
        if (viewerDeviceRowId) {
            const krows = await conn.query(
                'SELECT wrapped_key, wrapper_public_key FROM chat_group_device_keys WHERE group_id = ? AND device_id = ?',
                [group.id, viewerDeviceRowId]
            );
            mine = krows[0] || null;
        }

        // Devices of members that hold no envelope for this group yet — a
        // colleague who installed the app on a second device after the group was
        // created. Any member that *can* open the group re-wraps the key for
        // them (POST /groups/:id/keys), which is what keeps a new device from
        // being permanently locked out of existing groups.
        const missing = await conn.query(`
            SELECT d.id, d.public_key
            FROM chat_group_members gm
            JOIN chat_devices d ON d.chat_user_id = gm.user_id
            LEFT JOIN chat_group_device_keys k ON k.group_id = gm.group_id AND k.device_id = d.id
            WHERE gm.group_id = ? AND k.device_id IS NULL
        `, [group.id]);

        return {
            id: Number(group.id),
            name: group.name,
            creator_id: Number(group.creator_id),
            my_wrapped_key: mine ? mine.wrapped_key : null,
            wrapper_public_key: mine ? mine.wrapper_public_key : null,
            members: members.map(toUserJson),
            devices_missing_keys: missing.map(toDeviceJson),
        };
    }

    async function groupsForUser(conn, userId) {
        return conn.query(`
            SELECT g.* FROM chat_groups g
            JOIN chat_group_members m ON m.group_id = g.id
            WHERE m.user_id = ?
            ORDER BY g.id
        `, [userId]);
    }

    async function lastReadMessageId(conn, groupId, userId) {
        const rows = await conn.query(
            'SELECT last_read_message_id FROM chat_group_reads WHERE group_id = ? AND user_id = ?',
            [groupId, userId]
        );
        return rows[0] ? Number(rows[0].last_read_message_id) : 0;
    }

    // --- Deletion helpers ------------------------------------------------

    // Drop attachment blobs that no message references any more. Always call
    // this *after* the messages are gone (or tombstoned), never before.
    async function deleteOrphanedAttachments(conn, attachmentIds) {
        const ids = [...new Set(attachmentIds.map(Number).filter(Boolean))];
        if (!ids.length) return 0;
        const result = await conn.query(`
            DELETE FROM chat_attachments
            WHERE id IN (${ids.map(() => '?').join(',')})
              AND id NOT IN (SELECT attachment_id FROM chat_messages WHERE attachment_id IS NOT NULL)
        `, ids);
        return Number(result.affectedRows || 0);
    }

    // Hard-delete a set of messages with everything hanging off them: the
    // per-device body keys, and any attachment left without a referent.
    async function purgeMessages(conn, messages) {
        if (!messages.length) return;
        const ids = messages.map((m) => Number(m.id));
        const attachmentIds = messages.map((m) => m.attachment_id).filter((id) => id != null);
        const placeholders = ids.map(() => '?').join(',');
        await conn.query(`DELETE FROM chat_message_keys WHERE message_id IN (${placeholders})`, ids);
        await conn.query(`DELETE FROM chat_messages WHERE id IN (${placeholders})`, ids);
        await deleteOrphanedAttachments(conn, attachmentIds);
    }

    // --- Push helpers ----------------------------------------------------

    // Best-effort push to one device; never rejects, so a failed delivery can't
    // fail a send.
    async function pushToDevice(device, message) {
        if (!device || !device.proxy_user_id) return;
        try {
            const deviceToken = await lookupDeviceToken(device.proxy_user_id);
            if (!deviceToken) return;
            await sendPush(deviceToken, message);
        } catch (e) {
            console.error('[Chat] push failed:', e.message);
        }
    }

    // Fans a push out to every registered device of the given users, skipping the
    // device that sent the message (it already knows) — v4: an agent with an
    // iPhone and an iPad gets the notification on both.
    async function pushToUsers(conn, userIds, message, exceptDeviceRowId) {
        try {
            const devices = await devicesOfUsers(conn, userIds);
            const targets = devices.filter((d) => Number(d.id) !== Number(exceptDeviceRowId));
            await Promise.all(targets.map((d) => pushToDevice(d, message)));
        } catch (e) {
            console.error('[Chat] push fan-out failed:', e.message);
        }
    }

    const router = express.Router();
    // Attachments are posted as base64 inside the JSON body, so this router
    // needs a much larger limit than the proxy's default parser.
    router.use(express.json({ limit: JSON_BODY_LIMIT }));
    router.use(authenticate);

    // POST /register — upsert the caller in the directory, and this device in
    // chat_devices. Registering a second device no longer disturbs the first:
    // each keeps its own public key and its own push registration.
    router.post('/register', async (req, res) => {
        const { name, email, proxy_user_id, public_key, device_id } = req.body || {};
        if (!name) return res.status(400).json({ error: 'name is required.' });
        if (!device_id || !public_key) {
            return res.status(400).json({ error: 'device_id and public_key are required.' });
        }
        let conn;
        try {
            conn = await pool.getConnection();
            await conn.query(`
                INSERT INTO chat_users (instance_url, zammad_user_id, name, email)
                VALUES (?, ?, ?, ?)
                ON DUPLICATE KEY UPDATE name = VALUES(name), email = VALUES(email)
            `, [req.zammad.instanceUrl, req.zammad.userId, name, email || null]);
            const rows = await conn.query(
                'SELECT id FROM chat_users WHERE instance_url = ? AND zammad_user_id = ?',
                [req.zammad.instanceUrl, req.zammad.userId]
            );
            const chatUserId = Number(rows[0].id);

            await conn.query(`
                INSERT INTO chat_devices (chat_user_id, device_id, public_key, proxy_user_id)
                VALUES (?, ?, ?, ?)
                ON DUPLICATE KEY UPDATE public_key = VALUES(public_key), proxy_user_id = VALUES(proxy_user_id)
            `, [chatUserId, String(device_id).slice(0, 64), public_key, proxy_user_id || null]);

            const drows = await conn.query(
                'SELECT id, public_key FROM chat_devices WHERE chat_user_id = ? ORDER BY id',
                [chatUserId]
            );
            const mine = await conn.query(
                'SELECT id FROM chat_devices WHERE chat_user_id = ? AND device_id = ?',
                [chatUserId, String(device_id).slice(0, 64)]
            );

            res.json({
                chat_user_id: chatUserId,
                chat_device_id: Number(mine[0].id),
                devices: drows.map(toDeviceJson),
            });
        } catch (err) {
            console.error('[Chat] register error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // GET /users — all chat users on the caller's instance.
    router.get('/users', async (req, res) => {
        let conn;
        try {
            conn = await pool.getConnection();
            const users = await conn.query(
                'SELECT * FROM chat_users WHERE instance_url = ? ORDER BY name',
                [req.zammad.instanceUrl]
            );
            await attachDevices(conn, users);
            res.json(users.map(toUserJson));
        } catch (err) {
            console.error('[Chat] users error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // GET /conversations — direct and group summaries for the caller, newest first.
    router.get('/conversations', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            if (!me) return res.json([]);
            conn = await pool.getConnection();

            const result = [];

            // Direct conversations (group messages carry no partner).
            const partners = await conn.query(`
                SELECT DISTINCT CASE WHEN from_user_id = ? THEN to_user_id ELSE from_user_id END AS pid
                FROM chat_messages
                WHERE group_id IS NULL AND (from_user_id = ? OR to_user_id = ?)
            `, [me.id, me.id, me.id]);

            for (const { pid } of partners) {
                if (pid == null) continue;
                const prows = await conn.query('SELECT * FROM chat_users WHERE id = ?', [pid]);
                const partner = prows[0];
                if (!partner || partner.instance_url !== me.instance_url) continue;
                await attachDevices(conn, [partner]);
                const lrows = await conn.query(`
                    ${MESSAGE_SELECT}
                    WHERE m.group_id IS NULL
                      AND ((m.from_user_id = ? AND m.to_user_id = ?) OR (m.from_user_id = ? AND m.to_user_id = ?))
                    ORDER BY m.id DESC LIMIT 1
                `, [me.deviceRowId, me.id, pid, pid, me.id]);
                const urows = await conn.query(
                    // Tombstones don't count: a badge that opens onto "Message
                    // deleted" is noise, not news.
                    'SELECT COUNT(*) AS c FROM chat_messages WHERE group_id IS NULL AND deleted = 0 AND from_user_id = ? AND to_user_id = ? AND read_at IS NULL',
                    [pid, me.id]
                );
                result.push({
                    partner: toUserJson(partner),
                    group: null,
                    last_message: lrows[0] ? toMessageJson(lrows[0]) : null,
                    unread_count: Number(urows[0].c),
                });
            }

            // Group conversations.
            const groups = await groupsForUser(conn, me.id);
            for (const group of groups) {
                const lrows = await conn.query(`
                    ${MESSAGE_SELECT}
                    WHERE m.group_id = ?
                    ORDER BY m.id DESC LIMIT 1
                `, [me.deviceRowId, group.id]);
                const lastRead = await lastReadMessageId(conn, group.id, me.id);
                const urows = await conn.query(
                    'SELECT COUNT(*) AS c FROM chat_messages WHERE group_id = ? AND deleted = 0 AND from_user_id <> ? AND id > ?',
                    [group.id, me.id, lastRead]
                );
                result.push({
                    partner: null,
                    group: await groupJson(conn, group, me.deviceRowId),
                    last_message: lrows[0] ? toMessageJson(lrows[0]) : null,
                    unread_count: Number(urows[0].c),
                });
            }

            result.sort((a, b) => (b.last_message?.id || 0) - (a.last_message?.id || 0));
            res.json(result);
        } catch (err) {
            console.error('[Chat] conversations error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // POST /groups — create a group. wrapped_keys are opaque to the proxy.
    router.post('/groups', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            if (!me) return res.status(400).json({ error: 'Not registered for chat.' });
            const { name, member_ids, wrapped_keys } = req.body || {};
            if (!name || !Array.isArray(member_ids) || member_ids.length === 0) {
                return res.status(400).json({ error: 'name and member_ids are required.' });
            }

            // The creator is always a member, even if the client forgot to list them.
            const memberIds = [...new Set(member_ids.map((id) => parseInt(id, 10)).filter(Boolean).concat(Number(me.id)))];

            conn = await pool.getConnection();
            const members = await conn.query(
                `SELECT * FROM chat_users WHERE id IN (${memberIds.map(() => '?').join(',')})`,
                memberIds
            );
            if (members.length !== memberIds.length ||
                members.some((m) => m.instance_url !== me.instance_url)) {
                return res.status(400).json({ error: 'Invalid members.' });
            }

            // v4: the group key is wrapped per *device*, so every device of every
            // member can open it. Only accept envelopes addressed to a device that
            // actually belongs to one of the members.
            const memberDevices = await devicesOfUsers(conn, memberIds);
            const validDeviceIds = new Set(memberDevices.map((d) => Number(d.id)));
            const envelopes = [];
            for (const entry of Array.isArray(wrapped_keys) ? wrapped_keys : []) {
                const deviceId = parseInt(entry?.device_id, 10);
                if (!validDeviceIds.has(deviceId)) continue;
                if (typeof entry.wrapped_key !== 'string' || typeof entry.wrapper_public_key !== 'string') continue;
                envelopes.push([deviceId, entry.wrapped_key, entry.wrapper_public_key]);
            }
            if (!envelopes.length) {
                return res.status(400).json({ error: 'wrapped_keys must cover at least one member device.' });
            }

            await conn.beginTransaction();
            try {
                const info = await conn.query(
                    'INSERT INTO chat_groups (instance_url, name, creator_id) VALUES (?, ?, ?)',
                    [me.instance_url, String(name).slice(0, 255), me.id]
                );
                const groupId = Number(info.insertId);
                for (const id of memberIds) {
                    await conn.query(
                        'INSERT INTO chat_group_members (group_id, user_id) VALUES (?, ?)',
                        [groupId, id]
                    );
                }
                for (const [deviceId, wrappedKey, wrapperPublicKey] of envelopes) {
                    await conn.query(
                        'INSERT INTO chat_group_device_keys (group_id, device_id, wrapped_key, wrapper_public_key) VALUES (?, ?, ?, ?)',
                        [groupId, deviceId, wrappedKey, wrapperPublicKey]
                    );
                }
                await conn.commit();

                const grows = await conn.query('SELECT * FROM chat_groups WHERE id = ?', [groupId]);
                res.json(await groupJson(conn, grows[0], me.deviceRowId));
            } catch (e) {
                await conn.rollback();
                throw e;
            }
        } catch (err) {
            console.error('[Chat] create group error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // GET /groups — every group the caller belongs to.
    router.get('/groups', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            if (!me) return res.json([]);
            conn = await pool.getConnection();
            const groups = await groupsForUser(conn, me.id);
            const result = [];
            for (const group of groups) result.push(await groupJson(conn, group, me.deviceRowId));
            res.json(result);
        } catch (err) {
            console.error('[Chat] groups error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // POST /groups/:id/keys — hand a group key to member devices that don't have
    // it yet. Callable by any member (they can only pass on a key they could
    // already open), and only ever adds envelopes: an existing one is never
    // overwritten, so a member cannot swap the key out from under the group.
    router.post('/groups/:id/keys', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            if (!me) return res.status(400).json({ error: 'Not registered for chat.' });
            const groupId = parseInt(req.params.id, 10);
            const { wrapped_keys } = req.body || {};
            if (!groupId || !Array.isArray(wrapped_keys) || !wrapped_keys.length) {
                return res.status(400).json({ error: 'wrapped_keys are required.' });
            }

            conn = await pool.getConnection();
            if (!(await isGroupMember(conn, groupId, me.id))) {
                return res.status(403).json({ error: 'Not a member of this group.' });
            }

            // Only devices belonging to members of this group may be given a key.
            const memberRows = await conn.query('SELECT user_id FROM chat_group_members WHERE group_id = ?', [groupId]);
            const memberDevices = await devicesOfUsers(conn, memberRows.map((m) => m.user_id));
            const allowed = new Set(memberDevices.map((d) => Number(d.id)));

            let added = 0;
            for (const entry of wrapped_keys) {
                const deviceId = parseInt(entry?.device_id, 10);
                if (!allowed.has(deviceId)) continue;
                if (typeof entry.wrapped_key !== 'string' || typeof entry.wrapper_public_key !== 'string') continue;
                const result = await conn.query(
                    `INSERT INTO chat_group_device_keys (group_id, device_id, wrapped_key, wrapper_public_key)
                     VALUES (?, ?, ?, ?)
                     ON DUPLICATE KEY UPDATE group_id = group_id`,
                    [groupId, deviceId, entry.wrapped_key, entry.wrapper_public_key]
                );
                if (Number(result.affectedRows) === 1) added += 1;
            }
            res.json({ added });
        } catch (err) {
            console.error('[Chat] group key top-up error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // GET /messages?with=13&since=341 — direct messages, ascending.
    // GET /messages?group=3&since=341 — group messages, ascending.
    router.get('/messages', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const partnerId = parseInt(req.query.with, 10);
            const groupId = parseInt(req.query.group, 10);
            if (!me || (!partnerId && !groupId)) {
                return res.status(400).json({ error: 'with or group is required.' });
            }
            const since = parseInt(req.query.since, 10) || 0;
            conn = await pool.getConnection();

            let messages;
            if (groupId) {
                if (!(await isGroupMember(conn, groupId, me.id))) {
                    return res.status(403).json({ error: 'Not a member of this group.' });
                }
                messages = await conn.query(`
                    ${MESSAGE_SELECT}
                    WHERE m.group_id = ? AND m.id > ?
                    ORDER BY m.id ASC LIMIT 200
                `, [me.deviceRowId, groupId, since]);
            } else {
                messages = await conn.query(`
                    ${MESSAGE_SELECT}
                    WHERE m.group_id IS NULL
                      AND ((m.from_user_id = ? AND m.to_user_id = ?) OR (m.from_user_id = ? AND m.to_user_id = ?))
                      AND m.id > ?
                    ORDER BY m.id ASC LIMIT 200
                `, [me.deviceRowId, me.id, partnerId, partnerId, me.id, since]);
            }
            res.json(messages.map(toMessageJson));
        } catch (err) {
            console.error('[Chat] messages error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // POST /messages — send a direct (to_user_id) or group (group_id) message.
    router.post('/messages', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const { to_user_id, group_id, body, ticket_id, ticket_number,
                    attachment_id, attachment_name, attachment_mime,
                    sender_public_key, keys } = req.body || {};
            if (!me || (!to_user_id && !group_id) || !body) {
                return res.status(400).json({ error: 'body and one of to_user_id / group_id are required.' });
            }
            // v4: a direct message must carry the wrapped body key for every device
            // that is meant to read it. Without this the message would be
            // undecryptable for everyone, so reject it rather than store garbage.
            if (to_user_id && !group_id) {
                if (!sender_public_key || !Array.isArray(keys) || keys.length === 0) {
                    return res.status(400).json({ error: 'sender_public_key and keys are required for direct messages.' });
                }
            }

            // Rate limit per sender.
            const now = Date.now();
            const counter = sendCounters.get(me.id);
            if (!counter || now - counter.windowStart > SEND_WINDOW_MS) {
                sendCounters.set(me.id, { count: 1, windowStart: now });
            } else {
                counter.count += 1;
                if (counter.count > SEND_LIMIT) return res.status(429).json({ error: 'Rate limit exceeded.' });
            }

            conn = await pool.getConnection();

            // An attachment must exist and belong to the caller's instance.
            let attachmentId = null;
            if (attachment_id) {
                attachmentId = parseInt(attachment_id, 10);
                const arows = await conn.query('SELECT instance_url FROM chat_attachments WHERE id = ?', [attachmentId]);
                if (!arows[0] || arows[0].instance_url !== me.instance_url) {
                    return res.status(400).json({ error: 'Invalid attachment.' });
                }
            }

            let recipient = null;
            let group = null;
            if (group_id) {
                const groupId = parseInt(group_id, 10);
                const grows = await conn.query('SELECT * FROM chat_groups WHERE id = ?', [groupId]);
                group = grows[0];
                if (!group || group.instance_url !== me.instance_url || !(await isGroupMember(conn, groupId, me.id))) {
                    return res.status(403).json({ error: 'Not a member of this group.' });
                }
            } else {
                const rrows = await conn.query('SELECT * FROM chat_users WHERE id = ?', [to_user_id]);
                recipient = rrows[0];
                if (!recipient || recipient.instance_url !== me.instance_url) {
                    return res.status(400).json({ error: 'Invalid recipient.' });
                }
            }

            // For a direct message, only accept envelopes addressed to a device of
            // the recipient or of the sender — nobody else may be handed a key.
            let envelopes = [];
            if (!group) {
                const allowed = await devicesOfUsers(conn, [recipient.id, me.id]);
                const allowedIds = new Set(allowed.map((d) => Number(d.id)));
                for (const entry of keys) {
                    const deviceId = parseInt(entry?.device_id, 10);
                    if (!allowedIds.has(deviceId)) continue;
                    if (typeof entry.wrapped_key !== 'string') continue;
                    envelopes.push([deviceId, entry.wrapped_key]);
                }
                if (!envelopes.length) {
                    return res.status(400).json({ error: 'keys must cover at least one device of the recipient.' });
                }
            }

            const info = await conn.query(`
                INSERT INTO chat_messages
                    (from_user_id, to_user_id, group_id, body, ticket_id, ticket_number,
                     attachment_id, attachment_name, attachment_mime, sender_public_key)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `, [
                me.id,
                group ? null : recipient.id,
                group ? group.id : null,
                body,
                ticket_id || null,
                ticket_number || null,
                attachmentId,
                attachmentId ? (attachment_name || null) : null,
                attachmentId ? (attachment_mime || null) : null,
                group ? null : String(sender_public_key),
            ]);
            const insertedId = Number(info.insertId);
            for (const [deviceId, wrappedKey] of envelopes) {
                await conn.query(
                    'INSERT INTO chat_message_keys (message_id, device_id, wrapped_key) VALUES (?, ?, ?)',
                    [insertedId, deviceId, wrappedKey]
                );
            }
            const mrows = await conn.query(`${MESSAGE_SELECT} WHERE m.id = ?`, [me.deviceRowId, insertedId]);
            const message = mrows[0];

            // Best-effort push via the existing APNs pipeline. Never put the
            // message body in the push — it's E2E-encrypted ciphertext. The body
            // is sent as an APNS loc-key so the app localizes it on-device;
            // `body` is only a fallback for clients missing the key.
            if (group) {
                const members = await conn.query(
                    'SELECT user_id FROM chat_group_members WHERE group_id = ? AND user_id <> ?',
                    [group.id, me.id]
                );
                const payload = { chat_group_id: Number(group.id) };
                if (ticket_id) payload.ticketID = ticket_id;
                const push = {
                    title: `${me.name} @ ${group.name}`,
                    bodyLocKey: 'chat_new_message',
                    body: 'New message',
                    payload,
                };
                // Fire and forget — the sender shouldn't wait on APNs.
                pushToUsers(conn, members.map((m) => m.user_id), push, me.deviceRowId).catch(() => {});
            } else {
                const payload = { chat_from_user_id: Number(me.id) };
                if (ticket_id) payload.ticketID = ticket_id;
                // Every device of the recipient. The sender's own other devices are
                // deliberately not pushed — they pick the message up on their next
                // refresh, and "new message" from yourself reads as a bug.
                pushToUsers(conn, [recipient.id], {
                    title: me.name,
                    bodyLocKey: 'chat_new_message',
                    body: 'New message',
                    payload,
                }, me.deviceRowId).catch(() => {});
            }

            res.json(toMessageJson(message));
        } catch (err) {
            console.error('[Chat] send error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // POST /read — mark a direct conversation (with_user_id) or a group
    // (group_id) as read for the caller.
    router.post('/read', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const partnerId = parseInt(req.body?.with_user_id, 10);
            const groupId = parseInt(req.body?.group_id, 10);
            if (!me || (!partnerId && !groupId)) {
                return res.status(400).json({ error: 'with_user_id or group_id is required.' });
            }
            conn = await pool.getConnection();

            if (groupId) {
                if (!(await isGroupMember(conn, groupId, me.id))) {
                    return res.status(403).json({ error: 'Not a member of this group.' });
                }
                const rows = await conn.query('SELECT MAX(id) AS maxId FROM chat_messages WHERE group_id = ?', [groupId]);
                const maxId = rows[0]?.maxId != null ? Number(rows[0].maxId) : 0;
                await conn.query(`
                    INSERT INTO chat_group_reads (group_id, user_id, last_read_message_id)
                    VALUES (?, ?, ?)
                    ON DUPLICATE KEY UPDATE last_read_message_id = GREATEST(last_read_message_id, VALUES(last_read_message_id))
                `, [groupId, me.id, maxId]);
            } else {
                await conn.query(
                    'UPDATE chat_messages SET read_at = UTC_TIMESTAMP() WHERE group_id IS NULL AND from_user_id = ? AND to_user_id = ? AND read_at IS NULL',
                    [partnerId, me.id]
                );
            }
            res.json({ ok: true });
        } catch (err) {
            console.error('[Chat] read error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // DELETE /messages/:id — the sender deletes their own message for everyone.
    // The row is tombstoned rather than removed, so a client that reloads the
    // conversation sees it turn into "Message deleted" instead of silently
    // losing an id it already has.
    router.delete('/messages/:id', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const id = parseInt(req.params.id, 10);
            if (!me || !id) return res.status(400).json({ error: 'Invalid message id.' });

            conn = await pool.getConnection();
            const rows = await conn.query('SELECT * FROM chat_messages WHERE id = ?', [id]);
            const message = rows[0];
            if (!message) return res.status(404).json({ error: 'Message not found.' });
            if (Number(message.from_user_id) !== Number(me.id)) {
                return res.status(403).json({ error: 'Only the sender can delete this message.' });
            }
            if (message.deleted) return res.json({ ok: true }); // already a tombstone

            await conn.beginTransaction();
            try {
                await conn.query(`
                    UPDATE chat_messages
                    SET body = '', deleted = 1, ticket_id = NULL, ticket_number = NULL,
                        attachment_id = NULL, attachment_name = NULL, attachment_mime = NULL,
                        sender_public_key = NULL
                    WHERE id = ? AND from_user_id = ?
                `, [id, me.id]);
                // The wrapped body keys guard a body that no longer exists.
                await conn.query('DELETE FROM chat_message_keys WHERE message_id = ?', [id]);
                await conn.commit();
            } catch (e) {
                await conn.rollback();
                throw e;
            }

            await deleteOrphanedAttachments(conn, [message.attachment_id]);
            res.json({ ok: true });
        } catch (err) {
            console.error('[Chat] delete message error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // POST /conversations/delete — {with_user_id} wipes a direct conversation
    // for both participants; {group_id} deletes the group for everyone when the
    // caller created it, and is a plain "leave group" for any other member.
    router.post('/conversations/delete', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const partnerId = parseInt(req.body?.with_user_id, 10);
            const groupId = parseInt(req.body?.group_id, 10);
            if (!me || (!partnerId && !groupId)) {
                return res.status(400).json({ error: 'with_user_id or group_id is required.' });
            }
            conn = await pool.getConnection();

            if (groupId) {
                const grows = await conn.query('SELECT * FROM chat_groups WHERE id = ?', [groupId]);
                const group = grows[0];
                if (!group || group.instance_url !== me.instance_url ||
                    !(await isGroupMember(conn, groupId, me.id))) {
                    return res.status(403).json({ error: 'Not a member of this group.' });
                }
                const isCreator = Number(group.creator_id) === Number(me.id);

                await conn.beginTransaction();
                try {
                    if (isCreator) {
                        const messages = await conn.query(
                            'SELECT id, attachment_id FROM chat_messages WHERE group_id = ?', [groupId]
                        );
                        await purgeMessages(conn, messages);
                        await conn.query('DELETE FROM chat_group_device_keys WHERE group_id = ?', [groupId]);
                        await conn.query('DELETE FROM chat_group_members WHERE group_id = ?', [groupId]);
                        await conn.query('DELETE FROM chat_group_reads WHERE group_id = ?', [groupId]);
                        await conn.query('DELETE FROM chat_groups WHERE id = ?', [groupId]);
                    } else {
                        // Leaving takes this member's own rows only — the
                        // conversation stays intact for everyone else. Their
                        // devices' wrapped group keys go too, so nothing they
                        // could still decrypt is left behind, and /groups no
                        // longer lists it for them (which also stops the pushes).
                        const devices = await conn.query(
                            'SELECT id FROM chat_devices WHERE chat_user_id = ?', [me.id]
                        );
                        if (devices.length) {
                            const deviceIds = devices.map((d) => Number(d.id));
                            await conn.query(
                                `DELETE FROM chat_group_device_keys
                                 WHERE group_id = ? AND device_id IN (${deviceIds.map(() => '?').join(',')})`,
                                [groupId, ...deviceIds]
                            );
                        }
                        await conn.query('DELETE FROM chat_group_members WHERE group_id = ? AND user_id = ?', [groupId, me.id]);
                        await conn.query('DELETE FROM chat_group_reads WHERE group_id = ? AND user_id = ?', [groupId, me.id]);
                    }
                    await conn.commit();
                } catch (e) {
                    await conn.rollback();
                    throw e;
                }
            } else {
                const prows = await conn.query('SELECT instance_url FROM chat_users WHERE id = ?', [partnerId]);
                if (!prows[0] || prows[0].instance_url !== me.instance_url) {
                    return res.status(400).json({ error: 'Invalid partner.' });
                }
                await conn.beginTransaction();
                try {
                    const messages = await conn.query(`
                        SELECT id, attachment_id FROM chat_messages
                        WHERE group_id IS NULL
                          AND ((from_user_id = ? AND to_user_id = ?) OR (from_user_id = ? AND to_user_id = ?))
                    `, [me.id, partnerId, partnerId, me.id]);
                    await purgeMessages(conn, messages);
                    await conn.commit();
                } catch (e) {
                    await conn.rollback();
                    throw e;
                }
            }

            res.json({ ok: true });
        } catch (err) {
            console.error('[Chat] delete conversation error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // POST /attachments — store an encrypted blob, return its id.
    router.post('/attachments', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const { data, filename, mime_type } = req.body || {};
            if (!me || typeof data !== 'string' || !data) {
                return res.status(400).json({ error: 'data is required.' });
            }
            if (data.length > MAX_ATTACHMENT_BASE64) {
                return res.status(413).json({ error: 'Attachment too large.' });
            }
            const buffer = Buffer.from(data, 'base64');
            if (buffer.length === 0) return res.status(400).json({ error: 'Invalid base64 data.' });

            conn = await pool.getConnection();
            const info = await conn.query(`
                INSERT INTO chat_attachments (instance_url, uploader_id, data, filename, mime_type)
                VALUES (?, ?, ?, ?, ?)
            `, [me.instance_url, me.id, buffer, filename ? String(filename).slice(0, 255) : null,
                mime_type ? String(mime_type).slice(0, 128) : null]);
            res.json({ id: Number(info.insertId) });
        } catch (err) {
            console.error('[Chat] attachment upload error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    // GET /attachments/:id — the encrypted blob, base64 encoded.
    router.get('/attachments/:id', async (req, res) => {
        let conn;
        try {
            const me = await callerChatUser(req);
            const id = parseInt(req.params.id, 10);
            if (!me || !id) return res.status(400).json({ error: 'Invalid attachment id.' });
            conn = await pool.getConnection();
            const rows = await conn.query('SELECT * FROM chat_attachments WHERE id = ?', [id]);
            const attachment = rows[0];
            // Scoped per instance, like every other chat object.
            if (!attachment || attachment.instance_url !== me.instance_url) {
                return res.status(404).json({ error: 'Attachment not found.' });
            }
            res.json({
                data: Buffer.from(attachment.data).toString('base64'),
                filename: attachment.filename,
                mime_type: attachment.mime_type,
            });
        } catch (err) {
            console.error('[Chat] attachment download error:', err);
            res.status(500).json({ error: 'Database error.' });
        } finally {
            if (conn) conn.release();
        }
    });

    router.initSchema = initSchema;
    return router;
};
